name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Install Haxelib Libraries
        run: |
          haxelib setup --never
          haxelib install lime 8.1.2
          haxelib install openfl 9.3.2
          haxelib install flixel 5.5.0
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install hscript
          haxelib install actuate
          haxelib run lime setup flixel
          haxelib run lime setup android

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android APK
        run: haxelib run lime build android -release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PsychEngine-Mobile-APK
          path: export/release/android/bin/app/build/outputs/apk/release/
